### ISSUE TITLE
Strange tiny.requireAll

### ISSUE THREAD

**Issue by buckle2000** [bakpakin/tiny-ecs#10]
While `tiny.requireAll` works, it is hard to understand it. Why does it use `loadstring`?
Here is an equvalent function:

``` lua
local function requireAll(...)
    local required = {...}
    return function (_, entity)
        for i=1,#required do
            if entity[required[i]]==nil then
                return false  -- false means "don't include"
            end
        end
        return true
    end
end
```

**Comment by bakpakin** [comment]
It uses loadstring because that functionality was already added for string filters, like 

``` lua
tiny.filter 'componentA|(componentB&componentC)'
```

and for speed.

Since filters are probably the most performance critical part of an entity component system after the systems themselves, it is important that the default filters are pretty fast. tiny-ecs is not the only library to use code generation ECS - see [knife](https://github.com/airstruck/knife/blob/master/knife/system.lua)

Also, requireAll, and indeed all of the filter functions can take other filter functions as arguments.

``` lua
local myFilter = tiny.requireAll(tiny.filter 'a|b|c', 'myComponent', function(system, entity)
     return entity.size > 2 and entity.size < 10
end)

myFilter(nil, {a=true, myComponent=true, size=3}) --> true
myFilter(nil, {b=true, myComponent=true, size=11}) --> false
myFilter(nil, {c=true, myComponent=false, size=8}) --> false
myFilter(nil, {d=true, myComponent=true, size=6}) --> false
```

In the original versions of tiny-ecs, the filter functions were similar (almost exactly the same as) your example. After adding the shorthand function `tiny.filter`, The logic was already in place for code generation. Sure, its not exactly pretty, but it is fast, it works, and the code is there already.

**Comment by buckle2000** [comment]
Sorry I don't know that.

**Comment by bakpakin** [comment]
No need to apologize :)
