### ISSUE TITLE
Feathure request: support for empty components

### ISSUE THREAD

**Issue by Praron** [bakpakin/tiny-ecs#14]
Hi. Lib looks good, but, I think, empty components(flags) as strings in tables would be good for readability.
For example:
```
player = {
    position = Vector(100, 100),
    velocity = Vector(0, 0),
   'is_handles_input',
}
```
doesn't works for now, we need type `is_handles_input = true` or something like this, but it is looks not good, because it is not actually a boolean value.
I tried to understand how it works in source and change, but I failed D:

**Comment by Praron** [comment]
I just realized, that it will break access through `player.is_handles_input`, um. Maybe, preprocess it in `world.addEntity()` and transform this in `'is_handles_input = "flag"'`? It is harder to make but in result it is more beautiful API, I think.

**Comment by bakpakin** [comment]
Nothing is stopping you from doing components that way, just the built-in filters will not  work. While it could potentially work with the API, checking if an entity contained a component would require iterating through the array rather than just checking `player.is_handles_input`. This is slow and not really idiomatic Lua.

You could write a function to change your first form into the other, though, by iterating
through the array part of the table and changing the values to keys.

```lua
local function makeEntity(components)
    for i = 1, #components do
        local comp = components[i]
        components[comp] = true
        components[i] = nil
    end
    return components
end

-- Use like so
player = makeEntity {
    position = Vector(100, 100),
    velocity = Vector(0, 0),
    'is_handles_input'
}
```
I don't really feel the need to add this to the API.

**Comment by Praron** [comment]
Thanks for reply. Yes, you are right, this way is better and can help with some other things more.
