### ISSUE TITLE
Missing document

### ISSUE THREAD

**Issue by buckle2000** [bakpakin/tiny-ecs#9]
There is no document about `system.entities` nor `world.entities`. Also, there should description about return value of filter function:

> If the filter function returns false, the entity is not included in the system. Otherwise, yes.

**Comment by bakpakin** [comment]
~~There is no documentation about the system.entities~~ (System.entities is actually documented in the Systems section) and world.entities because they are internal, and most users shouldn't touch them. They have changed before, even when the rest of the API has not changed and may change in the future, although hopefully not.

Currently, though, they are each just lists of entities. As of the the latest commit, world.entities also contains the entities as keys to their index. For example, 

``` lua
local world = tiny.world()
local bob = world.add({name='bob'})
assert(world.entities[world.entities[bob]] == bob) -- Assert passes
```

As for the filter documentation, here is some from the docs:

> A Filter is a function that selects which Entities apply to a System.
> Filters take two parameters, the System and the Entity, and return a boolean
> value indicating if the Entity should be processed by the System.

Filters are functions that take a system and an entity and return if the entity is to be included in the system, as you have mentioned. I suppose it should be more explicit that a truthy value indicates inclusion, and a falsey value indicates exclusion.

**Comment by buckle2000** [comment]
Sometimes `processingSystem` is not enough, so I have to use `system.entities`.
Consider the following situation:
Each entity has a behavior (component), and each component has optional `preUpdate`, `update` and `postUpdate`.
If I have three entities `a` `b` `c`, and function calls should happen like this:
- a preUpdate
- b preUpdate
- c preUpdate
- a update
- b update
- c update
- a postUpdate
- b postUpdate
- c postUpdate

**Comment by bakpakin** [comment]
I have updated the docs for filter, and the other docs seem to be sufficient for now. I'm closing this.

**Comment by buckle2000** [comment]
Wait, I think `system.entities` and `world.entities` should appear in the document.
